### ISSUE TITLE
referencing files on your desktop

### ISSUE THREAD

**Issue by anonym0305** [rekalantar/covid19_detector#1]
Hi Reza: Thanks for sharing your good work on github.
Looks like you're referencing files on your desktop. Not sure if these files are on github as well.  
df = pd.read_csv(f'{path}/metadata.csv') 
Hope I'm not missing something.
Are you looking to share this work for others to build on?

**Comment by rekalantar** [comment]
Hi, 

Thanks for your message. The 'metadata.csv' file can be found within my repository. You will just need to replace the path with wherever you have cloned the repo to read the data. 

Let me know if you need more info.

**Comment by anonym0305** [comment]
Hi Reza, Thanks for answering my query. I appreciate.
I'm on a remote server and am using the following as the path
path = 'https://raw.githubusercontent.com/rekalantar/covid19_detector/master/metadata.csv'
instead of 
path = '/content/drive/My Drive/Covid-19'

I'm unable to understand how to change the path below, given the path I'm using above
# Initialize the variables for training
dataset_path = f'{path}/dataset'

**Comment by rekalantar** [comment]
You will not need the 'metadata.csv' file to run the code, I have just included it to visualise some metadata if required. I have already saved the images in the 'DATASET' folder for direct use. 

Alternatively, you can do `!wget https://github.com/rekalantar/covid19_detector/blob/master/metadata.csv` and then `df = pd.read_csv('/metadata.csv')` if you are using iPython.

**Comment by anonym0305** [comment]
Hi Reza - Thanks for your help. Actually, I was running the script on Colab
so the syntax would've been different. But anyways, looks like all's well.
I plan to modify the code somewhat for my academic research. I don't see a
reference to MIT license but I do see your statement
"...so everyone can use the free GPU resources available online to improve
the model."
So, I guess you're okay if I modify and use your model for my academic
research, obviously giving you due credit ?
~Sash

**Comment by rekalantar** [comment]
Hi Sash, 
IPython/Jupyter/Colab Notebook are all essentially the same thing, sharing the same syntax. So the code in my previous response should do the trick for you. Yes, you are more than welcome to use the model for your research.
